# Copyright 2024 The ChromiumOS Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

CROS_WORKON_COMMIT="556b55e169e541e5c0ee3be73a83ec9a5ca62221"
CROS_WORKON_TREE="dad8c3a31e9416be37dee896f50c06915ea684c6"
CROS_WORKON_PROJECT="chromiumos/third_party/kernel"
CROS_WORKON_LOCALNAME="kernel/v6.12"
CROS_WORKON_EGIT_BRANCH="chromeos-6.12"

# When USE=kernel_afdo is used, either AFDO_PROFILE_VERSION (for x86) or
# ARM_AFDO_PROFILE_VERSION (for ARM) must be specified. If both are specified,
# the profile is selected depending on the arch we're building for.
#
# TODO: Allow different versions for different CHROMEOS_KERNEL_SPLITCONFIGs

# By default, let cros-kernel define AFDO_LOCATION.  This is used in the
# kernel AFDO verify jobs to specify the location.
AFDO_LOCATION=""

# Auto-generated by PFQ, don't modify.
AFDO_PROFILE_VERSION=""
ARM_AFDO_PROFILE_VERSION=""

# Set AFDO_FROZEN_PROFILE_VERSION to freeze the afdo profiles.
# If non-empty, it overrides the value set by AFDO_PROFILE_VERSION.
# Note: Run "ebuild-<board> /path/to/ebuild manifest" afterwards to create new
# Manifest file.
AFDO_FROZEN_PROFILE_VERSION=""
ARM_AFDO_FROZEN_PROFILE_VERSION=""

# This must be inherited *after* EGIT/CROS_WORKON variables defined
inherit cros-workon cros-kernel

HOMEPAGE="https://www.chromium.org/chromium-os/chromiumos-design-docs/chromium-os-kernel"
DESCRIPTION="Chrome OS Linux Kernel 6.12"
KEYWORDS="*"
